### ISSUE TITLE
register.ftl and login-verify-email.ftl throw errors

### ISSUE THREAD

**Issue by PierreMouchan** [InseeFrLab/keycloakify#14] opened 2021-06-29 08:32 UTC
Hello, i made a fully custom theme using others deps as 'styled-components' and 'react-intl', everything is working well except the register and login verify email where both of those pages throw me the same error:

```
FTL stack trace ("~" means nesting-related):
        - Failed at: #local value = object[key]  [in template "login-verify-email.ftl" in macro "objectToJson" at line 70, column 21]
```

this is the code at line 70:

```
 <#attempt>
                    <#local value = object[key]>
                <#recover>
                    /* couldn't dereference ${key} of object */
                    <#continue>
                </#attempt>
```

Do you have any ideas of what is going on with this issue, the user cannot register and verify its email (he can only log in) ?
Thanks

**Comment by PierreMouchan** [comment] 2021-06-29 09:40
Actually it seems to not be the cause of the error, following the last paragraph from this:
https://freemarker.apache.org/docs/ref_directive_attempt.html

**Comment by garronej** [comment] 2021-06-29 11:23
having a look...

**Comment by garronej** [comment] 2021-06-29 11:53
@PierreMouchan I am very sorry for the inconvenience.  
I don't understand... the ligne that throws is within a try/catch... I will try to reproduce.

**Comment by garronej** [comment] 2021-06-29 12:08
@PierreMouchan I am sorry, I can't reproduce. 
I am fully committed to fix the issue but I will need some more info on your side. 
Can you give me a screenshot of the console when you load a failing page?

**Comment by PierreMouchan** [comment] 2021-06-29 12:13
> > @PierreMouchan I am sorry, I can't reproduce.
> > I am fully committed to fix the issue but I will need some more info on your side.
> > Can you give me a screenshot of the console when you load a failing page?
> 
> Here is the full screenshot ->
> <img alt="Screenshot 2021-06-29 at 14 11 05" width="1653" src="https://user-images.githubusercontent.com/38973205/123795107-ee2c7980-d8e3-11eb-88a1-34e0888dec08.png">

This throws an error inside the console but this does not 'crash' the app and it wasn't my initial issue, sorry for that

**Comment by garronej** [comment] 2021-06-29 12:31
Ok cool, 
So, just so you know, it is expected that a lot of errors appears in the Keycloak logs. To converts the `.ftl` values into a JavaScript object blindly we have to do things that throws. But it's all-right because every statement that can fail is inside a `<#attempt><#recorver>` block.   
You are not the first one however to be concerned by all the error in the Keycloak logs, maybe I should explain this in the README.    

However, back to our problem. As long as you don't get a 500 when loading the pages and as long as `window.kcContext` looks alright you should be able to implement the page....   

How is your `window.kcContext` looking on the problematic pages? (You can display it in the devlopper tool of your browser)

**Comment by PierreMouchan** [comment] 2021-06-29 12:34
> Ok cool,
> So, just so you know, it is expected that a lot of errors appears in the Keycloak logs. To converts the `.ftl` values into a JavaScript object blindly we have to do things that throws. But it's all-right because every statement that can fail is inside a `<#attempt><#recorver>` block.
> You are not the first one however to be concerned by all the error in the Keycloak logs, maybe I should explain this in the README.
> 
> However, back to our problem. As long as you don't get a 500 when loading the pages and as long as `window.kcContext` looks alright you should be able to implement the page....
> 
> How is your `window.kcContext` looking on the problematic pages? (You can display it in the devlopper tool of your browser)

Thanks for your quick answer ! The error was coming from our SMTP server (not getting the verification through email), i though it was from Keycloakify ! Sorry for that one !  There is no issue with the kcContext

**Comment by garronej** [comment] 2021-06-29 12:36
It's alright,  even our Keycloak expert got mislead by those errors.  
Thanks for reporting

**Closed by garronej** 2021-06-29 12:36 UTC
